# Generated by Django 4.0.2 on 2022-02-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_client_mobile_code_alter_mailing_mobile_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
    ]
