# Generated by Django 4.0.2 on 2022-02-20 10:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'.", regex='^7\\w{10}$')]),
        ),
        migrations.AlterField(
            model_name='request',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='mailing.client'),
        ),
        migrations.AlterField(
            model_name='request',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='mailing.mailing'),
        ),
    ]
