version: "3.7"

services:
  postgres:
    image: postgres:14.1-alpine
    env_file:
      - .env.dev
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  api:
    build:
      context: .
    ports:
      - "8000:8000"
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env.dev
    depends_on:
      - postgres

volumes:
  pg_data: